In [2]:
# broadcasting

import numpy as np


In [3]:
arr = np.array([2,3,4,5,6,5])
result = arr ** 2
print(result )

[ 4  9 16 25 36 25]


In [4]:
result + 10

array([14, 19, 26, 35, 46, 35])

In [6]:
arr1 = np.array([[2,3,5],[4,2,1]])
arr2 = np.array([1,2,3])
result = arr1 + arr2
print(result)

[[3 5 8]
 [5 4 4]]
