In [1]:
import numpy as np

In [2]:
 arr = np.array([1,3,4])

In [3]:
arr

array([1, 3, 4])

In [4]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.full((4,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.arange(3,56,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39, 41, 43, 45, 47, 49, 51, 53, 55])

In [11]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [13]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[3,2,34]])

In [14]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 3,  2, 34]])

In [15]:
myarr.shape

(4, 3)

In [16]:
myarr.size

12

In [17]:
myarr.ndim

2

In [18]:
myarr.dtype

dtype('int32')

In [19]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[3,2,34]], dtype='float32')

In [20]:
myarr.dtype

dtype('float32')

In [21]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 3.,  2., 34.]], dtype=float32)

In [22]:
n = myarr.astype('float64')

In [23]:
n

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 3.,  2., 34.]])

In [24]:
myarr.shape

(4, 3)

In [25]:
reshaped = myarr.reshape((3,4))

In [26]:
reshaped

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9.,  3.,  2., 34.]], dtype=float32)

In [27]:
myarr.reshape((2,6))

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9.,  3.,  2., 34.]], dtype=float32)

In [28]:
myarr.reshape((12,1))

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [ 3.],
       [ 2.],
       [34.]], dtype=float32)