In [1]:
import numpy as np

In [15]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[3,2,34]])

In [3]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 3.,  2., 34.]], dtype=float32)

In [16]:
flat = np.flatten()

AttributeError: module 'numpy' has no attribute 'flatten'

In [38]:
flat = arr.flatten()

In [39]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 3,  2, 34]])

In [40]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  3,  2, 34])

In [41]:
flat[0]

1

In [42]:
flat[3]

4

In [43]:
flat[3:7]

array([4, 5, 6, 7])

In [44]:
flat[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [45]:
flat[3:]

array([ 4,  5,  6,  7,  8,  9,  3,  2, 34])

In [46]:
flat[::3]

array([1, 4, 7, 3])

In [47]:
b = flat[3:7]

In [48]:
b

array([4, 5, 6, 7])

In [49]:
# b[0] = 444444

In [50]:
b

array([4, 5, 6, 7])

In [51]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  3,  2, 34])

In [56]:
b = flat[3:7].copy()

In [57]:
b

array([4, 5, 6, 7])

In [58]:
b[0] = 23432

In [60]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  3,  2, 34])

In [61]:
arr = np.array([2,343,45,56,34,5,76544,234,345,54,43])

In [63]:
arr[[1,4,5]]

array([343,  34,   5])

In [64]:
arr[arr>3]

array([  343,    45,    56,    34,     5, 76544,   234,   345,    54,
          43])

In [65]:
arr[arr>34]

array([  343,    45,    56, 76544,   234,   345,    54,    43])