In [1]:
import numpy as np
arr = np.array([[2,3,4],
                [4,5,6],
                [6,5,4]])

In [2]:
arr

array([[2, 3, 4],
       [4, 5, 6],
       [6, 5, 4]])

In [3]:
np.sum(arr, axis = 1)

array([ 9, 15, 15])

In [4]:
np.sum(arr, axis = 0)

array([12, 13, 14])

In [5]:
arr[0, 1]

3

In [6]:
arr[0:2,1:3]

array([[3, 4],
       [5, 6]])

In [7]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


In [8]:
# First sheet, second row, third column
print(arr3D[0, 1, 2])  # Output: 6

print(arr3D[:, 0, :])   # Get the first row from both sheets

6
[[1 2 3]
 [7 8 9]]


In [9]:
# Get all rows of the first column
first_col = arr[:, 0]
print(first_col)  # Output: [1 4 7]

[2 4 6]


In [10]:
# Get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :]
print(first_rows)

[[1 2 3]
 [7 8 9]]


In [11]:
# Replace all elements in column 1 with 0
arr[:, 1] = 0
print(arr)

[[2 0 4]
 [4 0 6]
 [6 0 4]]
